server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: org.wanbang.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射

template:
  purchaseOrderDeliverGoodsExcel: https://fosun-public-dev.oss-cn-hangzhou.aliyuncs.com/scm-pms/SRM-批量导入发货.xlsx

auth:
  paths:
    - /api/rpc/order/create
    - /api/rpc/order/cancel
    - /api/rpc/return/create
    - /api/rpc/return/cancel
    - /api/rpc/deliverGoods
    - /api/rpc/insert/pms/asn/backrewrite
    - /api/rpc/insert/pms/rtv/backrewrite
  authList:
    - clientKey: oms
      clientSecret: 9ffdb33ef5802146e555cf9e1082e314
    - clientKey: srm
      clientSecret: 3ee9b850c745f9c89b0faecc885980ca