server:
  port: 8999
  servlet:
    context-path: /

#mybatis-plush配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印与sql相关的日志

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master # 默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/demo_mybatis_plus7?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        tdengine1:
          url: jdbc:TAOS://HaoD:6030/demo?charset=utf-8
          driver-class-name: com.taosdata.jdbc.TSDBDriver
          username: root
          password: taosdata
        tdengine2:
          url: jdbc:TAOS://HaoD:6030/demo2?charset=utf-8
          driver-class-name: com.taosdata.jdbc.TSDBDriver
          username: root
          password: taosdata
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

