server:
  port: 8014
  servlet:
    context-path: /

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_mybatis_plus8?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379

#mybatis-plush配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印与sql相关的日志

access:
  key:
    property: dsd1sd2dr4