server:
  port: 8102
  servlet:
    context-path: /

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_mybatis_plus7?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root


  application:
    name: consumer
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，端口默认为1883，如果有多个，用逗号隔开
    url: tcp://127.0.0.1:1883
    #用户名
    username: ceshi
    #密码
    password: 123456
    #客户端id（不能重复）
    client:
      id: consumer-id
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: topic


#mybatis-plush配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印与sql相关的日志